name: gtex
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.0.5
    - r-irkernel=1.1
    - r-devtools
    - r-rmarkdown
    - r-knitr
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-stringr
    - r-forcats
    - r-cowplot
    - r-scales
    - r-lubridate